"""Data Models"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/models.ipynb.

# %% auto 0
__all__ = ['AnswerType', 'Question', 'ExtractionResult', 'LLMConfig']

# %% ../nbs/API/models.ipynb 3
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from enum import Enum
from datetime import datetime

# %% ../nbs/API/models.ipynb 4
class AnswerType(Enum):
    BOOLEAN = "boolean"
    ENUM = "enum" 
    INTEGER = "integer"
    FLOAT = "float"
    STRING = "string"
    DATE = "date"
    LIST = "list"


# %% ../nbs/API/models.ipynb 5
@dataclass
class Question:
    id: str
    text: str
    answer_type: AnswerType
    target_table: str
    target_field: str
    constraints: Dict[str, Any] = field(default_factory=dict)
    priority: int = 1
    group_key: Optional[str] = None  # For batching similar questions
    
    def __post_init__(self):
        if isinstance(self.answer_type, str):
            self.answer_type = AnswerType(self.answer_type)

# %% ../nbs/API/models.ipynb 6
@dataclass
class ExtractionResult:
    question_id: str
    raw_answer: str
    parsed_answer: Any
    confidence: Optional[float]
    is_valid: bool
    validation_error: Optional[str] = None
    timestamp: datetime = field(default_factory=datetime.now)

# %% ../nbs/API/models.ipynb 7
@dataclass
class LLMConfig:
    model_name: str = "gpt-3.5-turbo"
    temperature: float = 0.0
    max_tokens: Optional[int] = None
    api_key: Optional[str] = None
    base_url: Optional[str] = None
    timeout: int = 60
    max_retries: int = 3
